"
I offer a graph on a model which depend on external dependencies with a method outside jdk, meaning the signature need to be deducted, while providing the graph with theses external dependencies
"
Class {
	#name : 'CGContextualizerExample3Resource',
	#superclass : 'FamixAbstractJavaCGContextualizerBuilderTestResource',
	#category : 'Famix-CallGraphs-Contextualizer-Tests-Resources',
	#package : 'Famix-CallGraphs-Contextualizer-Tests',
	#tag : 'Resources'
}
